
FROM node:20-alpine
WORKDIR /app

ENV NODE_ENV=development

COPY package*.json ./
RUN if [ -f package-lock.json ]; then npm ci; else npm i; fi

COPY . .
EXPOSE 5173
CMD ["npm","run","dev","--","--host","0.0.0.0","--port","5173"]
